(define skk-use-skkserv? #f)
(define skk-skkserv-use-env? #f)
(define skk-skkserv-hostname "localhost")
(define skk-skkserv-portnum 1178)
(define skk-skkserv-address-family 'inet)
(define skk-dic-file-name "/usr/share/skk/SKK-JISYO.L")
(define skk-personal-dic-filename "/home/dnpp/.skk-jisyo")
(define skk-uim-personal-dic-filename "/home/dnpp/.skk-uim-jisyo")
